CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    estimatedTime TEXT,
    pin INTEGER NOT NULL,
    state INTEGER NOT NULL
) STRICT;
